[package]
name = "rlsof"
version = "0.1.0"
authors = ["Jesse Jaggars <jhjaggars@gmail.com>"]

[dependencies]
phf = { version = "0.8", features = ["macros"] }

[lib]
name = "rlsof"
path = "src/lib.rs"

[[bin]]
name = "rlsof"
path = "src/bin/main.rs"
