[package]
name = "rlsof"
version = "0.1.0"
authors = ["Jesse Jaggars <jhjaggars@gmail.com>"]

[lib]
name = "rlsof"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.10.1"
features = ["extension-module"]

[dependencies.phf]
version = "0.8"
features = ["macros"]
